import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import Layout from "~/application/widgets/layout";
import { NextPageWithLayout } from "~/application/app/_app";
import { api } from "~/utils/api";
import { ReactElement } from "react";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { GetStaticPropsContext } from "next";

const PAGE_NAME = "main";

const Page: NextPageWithLayout = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>TalentSync</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white"></main>
    </>
  );
};

Page.getLayout = function getLayout(page: ReactElement) {
  return <Layout page={`${PAGE_NAME}`}>{page}</Layout>;
};

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="">
      <p className="">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}

export async function getStaticProps({ locale }: GetStaticPropsContext) {
  locale = locale || "ru";

  return {
    props: {
      ...(await serverSideTranslations(locale, ["common", PAGE_NAME])),
    },
  };
}

export default Page;
