// import Navbar from './navbar'
// import Footer from './footer'

import Head from "next/head";
import { Navbar } from "../navbar";
import { Footer } from "../footer";

export function Layout({ children }: any) {
  return (
    <>
      <Head>
        <title>TalentSync</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="mx-auto max-w-screen-xl">{children}</main>
      <Footer />
    </>
  );
}
